# Generated by Django 4.0.6 on 2022-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=200)),
                ('이미지', models.ImageField(upload_to='blog_photopip')),
                ('내용', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
