# Generated by Django 4.0.6 on 2022-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='이미지',
            field=models.ImageField(upload_to='blog_photo'),
        ),
    ]
