# Generated by Django 4.0.6 on 2022-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_post_이미지'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
