# Generated by Django 4.0.6 on 2022-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='체크리스트1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='체크리스트2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='체크리스트3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
