# Generated by Django 4.0.6 on 2022-08-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_체크리스트1_post_체크리스트2_post_체크리스트3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='이미지',
        ),
    ]
