# Generated by Django 4.0.6 on 2022-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_post_이미지'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='썸네일',
            field=models.ImageField(blank=True, upload_to='blog_photo'),
        ),
    ]
