# Generated by Django 4.0.6 on 2022-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_썸네일'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='썸네일',
            field=models.ImageField(upload_to='blog_photo'),
        ),
    ]
